CREATE TABLE CUSTOMER (
    ID INT NOT NULL,
    NAME VARCHAR(255),
    AGE INT,
    EMAIL VARCHAR(255),
    CUSTOMER_ADDRESS_ID INT,
    PRIMARY KEY (ID)
);

ALTER TABLE CUSTOMER ADD CONSTRAINT FK_CUSTOMER_ADDRESS FOREIGN KEY (CUSTOMER_ADDRESS_ID) REFERENCES ADDRESS (ID);

CREATE SEQUENCE CUSTOMER_SEQ START WITH 1000 INCREMENT BY 1;
ALTER SEQUENCE CUSTOMER_SEQ NOCACHE;